config/routes.rb
Testme::Application.routes.draw do

  devise_for :users

  root :to => 'pages#index'

  get 'index' => 'pages#index'
  get 'work' => 'pages#work'
  get 'contact' => 'pages#contact'

  resources :users
  resources :investors
  resources :tasks
  resources :events
  resources :folders
  resources :documents

  resources :documents do
    member do
      get :download_attachment
    end
  end

  resources :investors do
    resources :events
    resources :tasks
  end
  
  resources :users do
    resources :events
  end

  resources :folder do
    resources :documents
  end

  resources :user do
    resources :folder do
      resources :documents
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:manager)
      can :read, :all
    elsif user.has_role?(:investor)
      can :read, :all
    else      
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :user
  belongs_to :role

end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  belongs_to :folder

  mount_uploader :attachment, FileUploader
  
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor

  has_many :participants
  has_many :attendees, :through => :participants, :source => :user

  accepts_nested_attributes_for :participants

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  has_many :documents

end

app/models/investor.rb
class Investor < ActiveRecord::Base

  has_many :users
  has_many :events
  has_many :tasks

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  belongs_to :user
  belongs_to :event

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :assignments
  has_many :users, :through => :assignments

  def self.admin
    find_by_name("admin")
  end   

  def self.manager
    find_by_name("manager")
  end

  def self.investor
    find_by_name("investor")
  end

end

app/models/setting.rb
STAGES = [1..4]

ROLESS = ["admin", "manager", "investor"]

app/models/task.rb
class Task < ActiveRecord::Base

  validates :task_owner_id, :presence => true
  validates :event_id, :presence => true

  belongs_to :user
  belongs_to :investor
  belongs_to :task_owner, :class_name => "User", :foreign_key => "task_owner_id"

end

app/models/task_user.rb
class TaskUser < ActiveRecord::Base

  belongs_to :task
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  scope :investors, where('investor_id IS NOT NULL')
  scope :employees, where('investor_id IS NULL')
  
  # if the assignments were all there this would work
  #scope :investors, joins(:assignments).where('assignments.role_id = 3')
  #scope :employees, joins(:assignments).where('assignments.role_id in (1,2)')
  
  def has_role(role)
    self.roles.find_by_name(role)
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :first_name, 
                  :last_name,
                  :investor_id,
                  :user_type,
                  :notes

  belongs_to :investor

  has_many :participants
  has_many :events, :through => :participants

  has_many :folders
  has_many :tasks
  has_many :assignments
  has_many :roles, :through => :assignments

  accepts_nested_attributes_for :participants
  
  def to_s
    [first_name, last_name].join(' ')
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def index
    @folders = Folder.all
    @breadcrumb = "Documents"
  end

  def show
    @folder = Folder.find(params[:id])
    @documents = @folder.documents
    @breadcrumb = "Documents > #{@folder.name}"
  end

  def new
    @folder = Folder.new
    @breadcrumb = "Documents > Add Folder"
  end

  def create
    @folder = Folder.new(params[:folder])
    
    if @folder.save
      redirect_to @folder
    else
      render :new
    end
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def update
    @folder = Folder.find(params[:id])
    
    if @folder.update_attributes(params[:folder])
      redirect_to folders_path
    else
      render :edit
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    redirect_to folders_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :work, :contact]

  def index
    @index_class = 'current'
  end
  
  def work
    @work_class = 'current'
  end
  
  def contact
    @contact_class = 'current'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.find(params[:id])
    @breadcrumb = "Investors > #{@investor.name} > #{@task.name}"
  end

  def new
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.new
    @breadcrumb = "Investors > #{@investor.name} > New Task"
  end

  def create
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.new(params[:task].merge(:user_id => current_user.id))
 
    if @task.save
      UserMailer.new_task(@task.task_owner, @task.user).deliver
      redirect_to investor_path(@investor)
    else
      render :new
    end
  end
 
  def edit
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.find(params[:id])
    @breadcrumb = "Investors > #{@investor.name} > #{@task.name} > Edit"
  end
  
  def update
    @investor = Investor.find(params[:investor_id])  
    @task = @investor.tasks.find(params[:id])
    
    if @task.update_attributes(params[:task])
      redirect_to @investor
    else
      render :edit
    end
  end
    
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    render :update do |page|
      #page << "#task_#{@task.id.to_s}"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(investor)
    [investor.first_name, investor.last_name].join(" ")
  end

  def nh(n,p=0)
    number_to_currency(n, :precision => p)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/folders/_form.html.erb
<%= form_for @folder do |f| %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :stage %><br />
		<%= f.select :stage, {'1:Potential' => 1, '2:Engaged' => 2, '3:Term Sheet' => 3, '4:Closed' => 4}, :include_blank => true %>
	</p>
	<p>
		<%= f.label :private %><br />
		<%= f.select :private, {'Yes' => 1, 'No' => 0} %>
	</p>
	<p>
		<%= f.label :investor_id, "Investor (if private)" %><br />
		<%= f.select :investor_id, (Investor.all.collect {|i| [i.name, i.id]}), :include_blank => true %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/folders/edit.html.erb
<div class='headers'>
	<h1>Folder Edit | <%= @folder.name %></h1>
</div>

<%= render 'form' %>

<div class='back_footer'>
	<%= link_to 'Back to folders', folders_path %>
</div>

app/views/folders/index.html.erb
<div class='headers'>
	<h1>Document Folders</h1>
</div>

<table>
	<tr>
		<th class='left'>Folder</th>
		<th class='left'>Documents</th>
		<th class='left'>Private</th>
		<th class='left'>Stage</th>
		<th class='left'>Investor ID</th>
		<th class='left'>User ID</th>
		<th class='left'></th>
		<th class='left'></th>
	</tr>
	<% @folders.each do |folder| %>
	<tr class='<%= cycle('odd','even')%>'>
		<td class='left'><%= link_to folder.name, folder %></td>
		<td class='left'><%=  %></td>
		<td class='left'><%= folder.private? ? 'Yes' : 'No' %></td>
		<td class='left'><%= folder.stage %></td>
		<td class='left'><%= folder.investor_id %></td>
		<td class='left'><%= folder.user_id %></td>
		<td class='left'><%= link_to 'Edit', edit_folder_path(folder) %></td>
		<td class='left'><%= link_to 'Destory', folder, :confirm => "Are you sure?", :method => :delete %></td>
	</tr>
	<% end %>
</table>

<br />
<%= link_to 'Add Folder', new_folder_path %>

app/views/folders/new.html.erb
<div class='headers'>
	<h1>New Folder</h1>
</div>

<%= render 'form' %>

<div class='back_footer'>
	<%= link_to 'Back to folders', folders_path %>
</div>

app/views/folders/show.html.erb
<div class='headers'>
	<h1><%= @folder.name %></h1>
</div>

<table>
	<tr>
		<th class='left'>Name</th>
		<th class='left'>File</th>
		<th class='left'>User ID</th>
		<th class='left'>Private</th>
		<th class='left'>Stage</th>
	</tr>
	<% @documents.each do |document| %>
	<tr class='<%= cycle('odd','even') %>'>
		<td class='left'><%= link_to document.name, folder_document_path(@folder, document) %></td>
		<td class='left'><%= document.attachment %></td>
		<td class='left'><%= document.user_id %></td>
		<td class='left'><%= document.private? ? 'Yes' : 'No' %></td>
		<td class='left'><%= document.stage %></td>
	</tr>
	<% end %>
</table>

<br />
<%= link_to 'Add Document', new_folder_document_path(@folder) %>

<div class='back_footer'>
	<%= link_to 'Back to Folders', folders_path %>
</div>