config/routes.rb
Testme::Application.routes.draw do

  devise_for :users

  root :to => 'pages#index'

  get 'index' => 'pages#index'
  get 'work' => 'pages#work'
  get 'contact' => 'pages#contact'

  resources :users
  resources :investors
  resources :tasks
  resources :events
  resources :folders
  resources :documents

  resources :documents do
    member do
      get :download_attachment
    end
  end

  resources :investors do
    resources :events
    resources :tasks
  end
  
  resources :users do
    resources :events
  end

  resources :folder do
    resources :documents
  end

  resources :user do
    resources :folder do
      resources :documents
    end
  end

end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  belongs_to :folder

  mount_uploader :attachment, FileUploader
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @folder = Folder.find(params[:folder_id])
    @documents = Document.all
  end

  def show
    @folder = Folder.find(params[:folder_id])
    @document = @folder.documents.find(params[:id])
    @breadcrumb = "Documents > #{@folder.name} > #{@document.name}"
  end

  def new
    @folder = Folder.find(params[:folder_id])
    @document = @folder.documents.new
    @breadcrumb = "Documents > #{@folder.name} > Add Document"
  end

  def create
    @folder = Folder.find(params[:folder_id])
    @document = @folder.documents.build(params[:document])
    
    if @document.save
      redirect_to folder_path(@folder)
    else
      render :new
    end
  end

  def edit
    @folder = Folder.find(params[:folder_id])
    @document = @folder.documents.find(params[:id])
    @breadcrumb = "Documents > #{@folder.name} > #{@document.name} > Edit"
  end

  def update
    @folder = Folder.find(params[:folder_id])
    @document = @folder.documents.find(params[:id])
    
    if @document.update_attributes(params[:document])
      redirect_to folder_path(@folder)
    else
      render :edit
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @folder = @document.folder
    @document.destroy
    redirect_to folder_path(@folder)
  end

  def download_attachment
    @document = Document.find(params[:id])
    redirect_to @document.attachment.url
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for [@folder, @document], :html => {:multipart => true} do |f| %>

	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :stage %><br />
		<%= f.select :stage, {'1:Potential' => 1, '2:Engaged' => 2, '3:Term Sheet' => 3, '4:Closed' => 4}, :include_blank => true %>
	</p>
	<p>
		<%= f.label :private %><br />
		<%= f.select :private, {'Yes' => 1, 'No' => 0} %>
	</p>
	<p>
		<%= f.label :investor_id, "Investor (if private)" %><br />
		<%= f.select :investor_id, (Investor.all.collect {|i| [i.name, i.id]}), :include_blank => true %>
	</p>
	<p>
		<%= f.file_field :attachment %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>

<br />
<%= link_to 'Back to document', folder_document_path(@folder, @document) %>

app/views/documents/index.html.erb
<div class='headers'>
	<h1>Documents Index</h1>
</div>

<table>
	<tr>
		<th class='left'>Name</th>
		<th class='left'>File</th>
		<th class='left'>User ID</th>
		<th class='left'>Private</th>
		<th class='left'>Stage</th>
		<th class='left'></th>
		<th class='left'></th>
		<th class='left'></th>
	</tr>
	<% @documents.each do |document| %>
	<tr class='<%= cycle('odd','even') %>'>
		<td class='left'><%= link_to document.name, folder_document_path(@folder, document) %></td>
		<td class='left'><%= document.attachment %></td>
		<td class='left'><%= document.user_id %></td>
		<td class='left'><%= document.private? ? "Yes" : "No" %></td>
		<td class='left'><%= document.stage %></td>
		<td class='left'><%= link_to 'Edit', edit_document_path(document) %></td>
		<td class='left'><%= link_to 'Destroy', document, :confirm => "Are you sure?", :method => :delete %></td>
		<td class='left'><%= link_to 'Download', "/uploads/document/file/2/super.rtf" %></td>
	</tr>
	<% end %>
</table>

<br />
<%= link_to 'Add Document', new_document_path %>

app/views/documents/new.html.erb
<h2>Add Document</h2>

<%= render 'form' %>

<br />
<%= link_to 'Back to documents', folder_path(@folder) %>

app/views/documents/show.html.erb
<h2><%= @document.name %></h2>

<table>
	<tr>
		<th>Description</th>
		<td><%= @document.description %></td>
	</tr>
	<tr>
		<th>File</th>
		<td><%= @document.attachment %></td>
	</tr>
	<tr>
		<th>User ID</th>
		<td><%= @document.user_id %></td>
	</tr>
	<tr>
		<th>Private</th>
		<td><%= @document.private? ? 'Yes' : 'No' %></td>
	</tr>
	<tr>
		<th>Stage</th>
		<td><%= @document.stage %></td>
	</tr>
	<tr>
		<th><%= link_to 'Download',  download_attachment_document_path(@document) %></th>
		<td></td>
	</tr>
</table>

<br />
<%= link_to 'Edit', edit_folder_document_path(@folder, @document) %> |
<%= link_to 'Destroy', @document, :confirm => "Are you sure?", :method => :delete %><br />
<%= link_to "Back to #{@folder.name.downcase} documents", @folder %>