config/routes.rb
Testme::Application.routes.draw do

  devise_for :users

  root :to => 'pages#index'

  get 'index' => 'pages#index'
  get 'work' => 'pages#work'
  get 'contact' => 'pages#contact'

  resources :users
  resources :investors
  resources :tasks
  resources :events
  resources :folders
  resources :documents

  resources :documents do
    member do
      get :download_attachment
    end
  end

  resources :investors do
    resources :events
    resources :tasks
  end
  
  resources :users do
    resources :events
  end

  resources :folder do
    resources :documents
  end

  resources :user do
    resources :folder do
      resources :documents
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:manager)
      can :read, :all
    elsif user.has_role?(:investor)
      can :read, :all
    else      
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :user
  belongs_to :role

end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  belongs_to :folder

  mount_uploader :attachment, FileUploader
  
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor

  has_many :participants
  has_many :attendees, :through => :participants, :source => :user

  accepts_nested_attributes_for :participants

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  has_many :documents

end

app/models/investor.rb
class Investor < ActiveRecord::Base

  has_many :users
  has_many :events
  has_many :tasks

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  belongs_to :user
  belongs_to :event

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :assignments
  has_many :users, :through => :assignments

  def self.admin
    find_by_name("admin")
  end   

  def self.manager
    find_by_name("manager")
  end

  def self.investor
    find_by_name("investor")
  end

end

app/models/setting.rb
STAGES = [1..4]

ROLESS = ["admin", "manager", "investor"]

app/models/task.rb
class Task < ActiveRecord::Base

  validates :task_owner_id, :presence => true
  validates :event_id, :presence => true

  belongs_to :user
  belongs_to :investor
  belongs_to :task_owner, :class_name => "User", :foreign_key => "task_owner_id"

end

app/models/task_user.rb
class TaskUser < ActiveRecord::Base

  belongs_to :task
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  scope :investors, where('investor_id IS NOT NULL')
  scope :employees, where('investor_id IS NULL')
  
  # if the assignments were all there this would work
  #scope :investors, joins(:assignments).where('assignments.role_id = 3')
  #scope :employees, joins(:assignments).where('assignments.role_id in (1,2)')
  
  def has_role(role)
    self.roles.find_by_name(role)
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :first_name, 
                  :last_name,
                  :investor_id,
                  :user_type,
                  :notes

  belongs_to :investor

  has_many :participants
  has_many :events, :through => :participants

  has_many :folders
  has_many :tasks
  has_many :assignments
  has_many :roles, :through => :assignments

  accepts_nested_attributes_for :participants
  
  def to_s
    [first_name, last_name].join(' ')
  end

end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController

  def index
    @investors = Investor.all
    @breadcrumb = 'Investors'
  end

  def show
    @investor = Investor.find(params[:id])
    @events = @investor.events.order('date DESC').all
    @tasks = @investor.tasks.order('due_date ASC').all
    @users = User.where('investor_id = ?', @investor.id)
    @breadcrumb = "Investors > #{@investor.name}"
  end

  def new
    @investor = Investor.new
    @breadcrumb = "Investors > Add Investor"
  end
  
  def create
    @investor = Investor.new(params[:investor])
    if @investor.save
      redirect_to investors_path
    else
      render :new
    end
  end
    
  def edit
    @investor = Investor.find(params[:id])  
    @breadcrumb = "Investors > #{@investor.name} > Edit"
  end
  
  def update
    @investor = Investor.find(params[:id])

    if @investor.update_attributes(params[:investor])
      redirect_to @investor
    else
      render :edit
    end
  end
  
  def destroy
    @investor = Investor.find(params[:id])
    @investor.destroy
    redirect_to investors_path
  end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :work, :contact]

  def index
    @index_class = 'current'
  end
  
  def work
    @work_class = 'current'
  end
  
  def contact
    @contact_class = 'current'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.find(params[:id])
    @breadcrumb = "Investors > #{@investor.name} > #{@task.name}"
  end

  def new
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.new
    @breadcrumb = "Investors > #{@investor.name} > New Task"
  end

  def create
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.new(params[:task].merge(:user_id => current_user.id))
 
    if @task.save
      UserMailer.new_task(@task.task_owner, @task.user).deliver
      redirect_to investor_path(@investor)
    else
      render :new
    end
  end
 
  def edit
    @investor = Investor.find(params[:investor_id])
    @task = @investor.tasks.find(params[:id])
    @breadcrumb = "Investors > #{@investor.name} > #{@task.name} > Edit"
  end
  
  def update
    @investor = Investor.find(params[:investor_id])  
    @task = @investor.tasks.find(params[:id])
    
    if @task.update_attributes(params[:task])
      redirect_to @investor
    else
      render :edit
    end
  end
    
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    render :update do |page|
      #page << "#task_#{@task.id.to_s}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @admin_users = User.where(role = 1)
    # @manager_users = User.where(:manager => true)
    # @investor_users = User.where(:investor => true)
    @users = User.all
    @breadcrumb = "Users"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(investor)
    [investor.first_name, investor.last_name].join(" ")
  end

  def nh(n,p=0)
    number_to_currency(n, :precision => p)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/investors/_form.html.erb
<%= form_for @investor do |f| %>

	<p><%= f.label :name, "Investment Group" %><br />
	<%= f.text_field :name  %></p>
	
	<p><%= f.label :street %><br />
	<%= f.text_field :street  %></p>
	
	<p><%= f.label :city %><br />
	<%= f.text_field :city %></p>
	
	<p><%= f.label :state %><br />
		    <%= f.select :state, ['AK','AL','AR','AZ','CA','CO','CT','DC','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY'], :include_blank => true %></p>
	
	<p><%= f.label :zipcode %><br />
	<%= f.text_field :zipcode %></p>

	<p><%= f.label :stage %><br />
	<%= f.select :stage, {'1:Potential' => 1, '2:Engaged' => 2, '3:Term Sheet' => 3, '4:Closed' => 4}, :include_blank => true %></p>
	
	<p><%= f.label :status %><br />
	<%= f.text_area :status, :size => '40x10' %></p>

	<p><%= f.label :probability %></p>
	<%= f.select :probability, ['high', 'moderate', 'low'], :include_blank => true %>
	
	<p><%= f.label :assets %><br />
	<%= f.text_field :assets %></p>
	
	<p><%= f.label :potential_commitment %><br />
	<%= f.text_field :potential_commitment %></p>

	<p><%= f.label :expected_close %><br />
	<%= f.date_select :expected_close, :include_blank => true %></p>

	<p><%= f.label :closed_commitment %><br />
	<%= f.text_field :closed_commitment %></p>
	
	<p><%= f.submit :Submit %></p>

<% end %>

app/views/investors/edit.html.erb
<div class='headers'>
	<h1>Edit Investor | <%= @investor.name %></h1>
</div>

<%= render 'form' %>

<div class='back_footer'>
	<%= link_to 'Back to investors', investors_path %>
</div>

app/views/investors/index.html.erb
<div class='headers'>
	<h1>Current Investors</h1>
</div>

<table>
	<tr class='header_row'>
		<th class='left'>Investment Group</th>
		<th class='left'>Status</th>
		<th class='left'>Stage</th>
		<th class='left'>Assets</th>
		<th class='left'>Potential Commitment</th>
		<th class='left'>Expected Close</th>
		<th class='left'>Probability</th>
		<th class='left'>Closed Commitment</th>
		<th class='left'></th>
		<th class='left'></th>
	</tr>
	<% @investors.each do |investor| %>
	<tr class="<%= cycle('odd','even') %>">
		<td class='left'><%= link_to investor.name, investor %></td>
		<td class='left'><%= truncate(investor.status, :length => 60, :omission => "...") %></td>
		<td class='left'><%= investor.stage %></td>
		<td class='left'><%= nh(investor.assets) %></td>
		<td class='left'><%= nh(investor.potential_commitment) %></td>
		<td class='left'><%= investor.expected_close %></td>
		<td class='left'><%= investor.probability %></td>
		<td class='left'><%= investor.closed_commitment %></td>
		<td class='left'><%= link_to 'Edit', edit_investor_path(investor) %></td>
		<td class='left'><%= link_to 'Destroy', investor, :confirm => "Are you sure?", :method => :delete %></td>
	</tr>
	<% end %>
</table>

<br />
<%= link_to "New Investor", new_investor_path %>

app/views/investors/new.html.erb
<div class='headers'>
	<h1>New Investor</h1>
</div>

<%= render 'form' %>

<div class='back_footer'>
	<%= link_to 'Back to investors', investors_path %>
</div>

app/views/investors/show.html.erb
<div class='headers'>
	<h1><%= @investor.name %></h1>
</div>

<div class='investor_main_container'>
<div class='investor_container'>
	<div id='object_status'>
		<div id='left_status'>
			Status
		</div>
		<div id='right_status'>
			<%= truncate(@investor.status, :length => 300, :omission => "...") %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Stage
		</div>
		<div id='right'>
			<%= @investor.stage %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Potential Commitment
		</div>
		<div id='right'>
			<%= nh(@investor.potential_commitment) %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Probability
		</div>
		<div id='right'>
			<%= @investor.probability.humanize %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Total Assets
		</div>
		<div id='right'>
			<%= nh(@investor.assets) %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Expected Close
		</div>
		<div id='right'>
			<%= @investor.expected_close %>
		</div>
	</div>
	<div id='object'>
		<div id='left'>
			Closed Commitment
		</div>
		<div id='right'>
			<%= nh(@investor.closed_commitment) %>
		</div>
	</div>
</div>
<div class='date_container'>
	<div id='right'>
		<strong>Address</strong><br />
		<%= @investor.street %><br />
		<%= "#{@investor.city}, #{@investor.state} #{@investor.zipcode}"%>
		<p>
			<%= link_to 'Edit', edit_investor_path %> | <%= link_to "Destroy", @investor, :confirm => "Are you sure?", :method => :delete %>
		</p>
	</div>
</div>
</div>

<div class='headers'>
	<h2>Contacts</h2>
</div>

	<table>
		<tr class='header_row'>
			<th class='leftfirst'>Name</th>
			<th class='left'>Email</th>
			<th class='left'>Phone</th>
			<th class='left'>Notes</th>
		</tr>
		<% @users.each do |user| %>
		<tr class="<%= cycle('odd','even') %>">
			<td class='left'><%= [user.first_name, user.last_name].join(" ") %></td>
			<td class='left'><%= user.email %></td>
			<td class='left'><%= user.phone %></td>			
			<td class='left'><%= user.notes %></td>						
		</tr>
		<% end %>
	</table>

<div class='headers'>
	<h2>Action Items</h2>
</div>

	<table>
		<tr class='header_row'>
			<th class='leftfirst'>Name</th>
			<th class='leftnotes'>Description</th>
			<th class='left'>Due Date</th>
			<th class='left'>Assigned By</th>
			<th class='left'>Assigned To</th>
			<th class='left'>Completed</th>
			<th class='left'>Compelted Date</th>
			<th class='left'>Event ID</th>
			<th class='left'>Investor</th>
			<th></th>
			<th></th>
		</tr>
		<% @tasks.each do |task| %>
		<tr class="<%= cycle('odd','even') %>" id="tasks_<%= task.id.to_s %>">
			<td class='left'><%= link_to task.name, investor_task_path(@investor, task) %></td>
			<td class='left'><%= truncate(task.description, :length => 25, :omission => "...") %></td>
			<td class='left'><%= task.due_date %></td>
			<td class='left'><%= task.user.first_name %></td>
			<td class='left'><%= task.task_owner.first_name %></td>
			<td class='left'><%= task.completed? ? 'Yes' : 'No' %></td>
			<td class='left'><%= task.completed_date %></td>
			<td class='left'><%= task.event_id %></td>
			<td class='left'><%= task.investor.name %></td>
			<td class='left'><%= link_to 'Edit', edit_investor_task_path(@investor, task) %></td>
			<td class='left'>
				<%= link_to 'Destroy', "#", :onclick => 'return false;', :class => 'destroy', 'data-model' => 'tasks', 'data-id' => task.id.to_s  %>
			</td>
		</tr>
		<% end %>
	</table>
<br />
<%= link_to 'Add Task', new_investor_task_path(@investor) %>

<div class='headers'>
	<h2>Events</h2>
</div>

	<table>
		<tr class='header_row'>
			<th class='left'>Date</th>
			<th class='left'>Name</th>
			<th class='left'>Type</th>
			<th class='left'>Notes</th>
			<th class='left'>Investor ID</th>
			<th class='left'>Created By</th>
			<th></th>
			<th></th>			
		</tr>
		<% @investor.events.each do |event| %>
		<tr class='<%= cycle('odd','even') %>'  id="events_<%= event.id.to_s %>">
			<td class='left'><%= event.date %></td>
			<td class='left'><%= link_to event.name, investor_event_path(@investor, event) %></td>
			<td class='left'><%= event.event_type %></td>
			<td class='left'><%= truncate(event.notes, :length => 50, :omission => "...") %></td>
			<td class='left'><%= event.investor.name %></td>
			<td class='left'><%= event.user.first_name %></td>
			<td class='left'><%= link_to 'Edit', edit_investor_event_path(@investor, event) %></td>
			<td class='left'>
				<%= link_to 'Destroy', "#", :onclick => 'return false;', :class => 'destroy', 'data-model' => 'events', 'data-id' => event.id.to_s  %>
			</td>
		</tr>
		<% end %>
	</table>

<br />
<%= link_to "Add Event", new_investor_event_path(@investor) %>

<div class='back_footer'>
	<%= link_to "< Back", investors_path %>
</div>