config/routes.rb
Testme::Application.routes.draw do

  devise_for :users

  root :to => 'pages#index'

  get 'index' => 'pages#index'
  get 'work' => 'pages#work'
  get 'contact' => 'pages#contact'

  resources :users
  resources :investors
  resources :tasks
  resources :events
  resources :folders
  resources :documents

  resources :documents do
    member do
      get :download_attachment
    end
  end

  resources :investors do
    resources :events
    resources :tasks
  end
  
  resources :users do
    resources :events
  end

  resources :folder do
    resources :documents
  end

  resources :user do
    resources :folder do
      resources :documents
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:manager)
      can :read, :all
    elsif user.has_role?(:investor)
      can :read, :all
    else      
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :user
  belongs_to :role

end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  belongs_to :folder

  mount_uploader :attachment, FileUploader
  
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor

  has_many :participants
  has_many :attendees, :through => :participants, :source => :user

  accepts_nested_attributes_for :participants

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  belongs_to :user
  belongs_to :investor
  has_many :documents

end

app/models/investor.rb
class Investor < ActiveRecord::Base

  has_many :users
  has_many :events
  has_many :tasks

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  belongs_to :user
  belongs_to :event

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :assignments
  has_many :users, :through => :assignments

  def self.admin
    find_by_name("admin")
  end   

  def self.manager
    find_by_name("manager")
  end

  def self.investor
    find_by_name("investor")
  end

end

app/models/setting.rb
STAGES = [1..4]

ROLESS = ["admin", "manager", "investor"]

app/models/task.rb
class Task < ActiveRecord::Base

  validates :task_owner_id, :presence => true
  validates :event_id, :presence => true

  belongs_to :user
  belongs_to :investor
  belongs_to :task_owner, :class_name => "User", :foreign_key => "task_owner_id"

end

app/models/task_user.rb
class TaskUser < ActiveRecord::Base

  belongs_to :task
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  scope :investors, where('investor_id IS NOT NULL')
  scope :employees, where('investor_id IS NULL')
  
  # if the assignments were all there this would work
  #scope :investors, joins(:assignments).where('assignments.role_id = 3')
  #scope :employees, joins(:assignments).where('assignments.role_id in (1,2)')
  
  def has_role(role)
    self.roles.find_by_name(role)
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :first_name, 
                  :last_name,
                  :investor_id,
                  :user_type,
                  :notes

  belongs_to :investor

  has_many :participants
  has_many :events, :through => :participants

  has_many :folders
  has_many :tasks
  has_many :assignments
  has_many :roles, :through => :assignments

  accepts_nested_attributes_for :participants
  
  def to_s
    [first_name, last_name].join(' ')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :work, :contact]

  def index
    @index_class = 'current'
  end
  
  def work
    @work_class = 'current'
  end
  
  def contact
    @contact_class = 'current'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(investor)
    [investor.first_name, investor.last_name].join(" ")
  end

  def nh(n,p=0)
    number_to_currency(n, :precision => p)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Clearview Solutions | Professional Investors</title>

	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application", "custom"  %>
	<%= javascript_include_tag "jquery.min.js", "jquery-ui.min.js" %>
	<%= javascript_include_tag 'rails.js', 'application.js' %>

	<!--  REPLACING THE ABOVE javascript_link_tag CONTENT WITH: :defaults MAKES THE DESTROY ACTION WORK - OTHERWISE, ONLY THE CALENDAR POPUP WORKS -->

  <%= csrf_meta_tag %>

</head>
<body>

<% if user_signed_in? %>

	<div id="investor_holder">
		<div id="investor_menu">
			<ul>
				<li>Welcome <%= link_to current_user.first_name, edit_user_registration_path %>!</li>
				<li><%= link_to "Investors", investors_path %></li>
				<li><%= link_to "Events", events_path %></li>
				<li><%= link_to "Tasks", tasks_path %></li>
				<li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Documents", folders_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path %></li>
			</ul>
		</div>
	</div>

<% else %>

	<div class='logo_container'>
		<div id="logo" style="text-align:center; margin-top: 30px; margin-bottom:30px"><%= link_to image_tag('logo.png', :border => 0), root_path %></a>
			<div id="investor_container">
			</div>	
		</div>
	</div>

<% end %>

<div class="body_container">
	<div id="breadcrumb">
		<%= @breadcrumb %>
	</div>
	<%= alert %>
	<%= notice %>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Clearview Solutions | Professional Investors</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

	<% if user_signed_in? %>

		<div id="investor_holder">
			<div id="investor_menu">
				<ul>
					<li>Welcome <%= link_to current_user.first_name, edit_user_registration_path %>!</li>
					<li><%= link_to "Investors", investors_path %></li>
					<li><%= link_to "Events", events_path %></li>
					<li><%= link_to "Users", users_path %></li>
					<li><%= link_to "Documents", folders_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path %></li>
				</ul>
			</div>
		</div>

	<% else %>

		<div class='logo_container'>
			<div id="logo"><a href="index.html"><img src="images/logo.png" border="0"></a>
				<div id="investor_container">
					<div id="investor_login">
						<%= link_to 'Investor Login', new_user_session_path %>
					</div>
				</div>	
			</div>
		</div>

	<% end %>

<div class="main_body_container">
	<div class="main_body">
	 	<div id="alert"><%= alert %></div>
	 	<div id="notice"><%= notice %></div>	
		<%= yield %>
	</div>
</div>

<div class="main_menu_container">
	<div class="main_menu">
		<div id="menu">
			<%= link_to 'ABOUT', :index, :class => "#{@index_class}" %>
			<%= link_to 'WORK', :work, :class => "#{@work_class}" %>
			<%= link_to 'CONTACT', :contact, :class => "#{@contact_class}" %>
		</div>
</div>

<div class="footer_container">
	<div id="footer">Clearview Solutions, LLC  |  &copy; <%= Time.now.year %></div>
</div>

</body>
</html>

app/views/pages/contact.html.erb
<p>Please send all inquiries to: info@clearview-solutions.net.</p>

app/views/pages/index.html.erb
<p>Clearview Solutions, LLC. is an investment company consisting of professional investors and consultants. Our primary areas of focus include the purchase, sale, and development of multi-family, residential and commercial real estate. Our team sources, structures and executes deals of all varieties, typically in niche or underserved markets. In addition to direct investment, Clearview provides consulting services on deal structuring, execution and strategic liquidation.</p>

app/views/pages/work.html.erb
<p>Clearview primarily targets investment opportunities with significant value-add potential, particularly where Clearview professionals can create value via deal structuring, creative financing alternatives, aggressive renovation, distressed buyouts, or strategic paths to liquidation. Our primary focus areas include: commercial, multi-family and distressed real estate opportunities.</p>